"""empty message

Revision ID: 90882a6f15c3
Revises: 4c1925c85ef5
Create Date: 2020-03-22 12:33:14.080369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90882a6f15c3'
down_revision = '4c1925c85ef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('totals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('totals')
    # ### end Alembic commands ###
