"""empty message

Revision ID: ca9ba145768e
Revises: 90882a6f15c3
Create Date: 2020-03-24 18:50:13.509080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ca9ba145768e'
down_revision = '90882a6f15c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('country', table_name='locations')
    op.create_unique_constraint(None, 'locations', ['country'])
    op.drop_column('locations', 'latitude')
    op.drop_column('locations', 'province')
    op.drop_column('locations', 'longitude')
    op.drop_column('locations', 'country_code')
    op.drop_column('locations', 'last_updated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('last_updated', mysql.DATETIME(), nullable=True))
    op.add_column('locations', sa.Column('country_code', mysql.VARCHAR(length=10), nullable=False))
    op.add_column('locations', sa.Column('longitude', mysql.DECIMAL(precision=10, scale=0), nullable=False))
    op.add_column('locations', sa.Column('province', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('locations', sa.Column('latitude', mysql.DECIMAL(precision=10, scale=0), nullable=False))
    op.drop_constraint(None, 'locations', type_='unique')
    op.create_index('country', 'locations', ['country', 'province'], unique=True)
    # ### end Alembic commands ###
